### ISSUE TITLE
数据集相关问题

### ISSUE THREAD

**Issue by lulala-haha** [windforfurture/DTCA#5]
您好，您的工作非常出色，在学习您代码的过程中，您的数据集的路径为datasets/finetune/dualc/'2015'/input.pt  而我下载到的twitter15、twitter17数据集是.txt .tsv .jpg格式的，我想请教一下这些数据需要经过什么处理才能得到.pt格式的数据集呢？或者您可以提供相关的.pt数据集吗？期待您的回复！

**Comment by windforfurture** [comment]
请看utils/TrainInputProcess.py 文件，readme第三步也有写

**Comment by lulala-haha** [comment]
非常感谢
